"""add default to orders.status

Revision ID: 7174e84c7be5
Revises: fff11fd93a39
Create Date: 2025-12-24 16:01:45.070677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7174e84c7be5'
down_revision: Union[str, Sequence[str], None] = 'fff11fd93a39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('order_items_order_id_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('pending', 'paid', 'cancelled', 'shipped', name='orderstatus'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_constraint(op.f('orders_user_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_user_id_fkey'), 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.alter_column('orders', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('pending', 'paid', 'cancelled', 'shipped', name='orderstatus'),
               existing_nullable=False)
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_order_id_fkey'), 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
